OTHER_FILES += \
    $$PWD/requests/packages/chardet/__init__.py \
    $$PWD/requests/packages/chardet/big5freq.py \
    $$PWD/requests/packages/chardet/big5prober.py \
    $$PWD/requests/packages/chardet/chardetect.py \
    $$PWD/requests/packages/chardet/chardistribution.py \
    $$PWD/requests/packages/chardet/charsetgroupprober.py \
    $$PWD/requests/packages/chardet/charsetprober.py \
    $$PWD/requests/packages/chardet/codingstatemachine.py \
    $$PWD/requests/packages/chardet/compat.py \
    $$PWD/requests/packages/chardet/constants.py \
    $$PWD/requests/packages/chardet/cp949prober.py \
    $$PWD/requests/packages/chardet/escprober.py \
    $$PWD/requests/packages/chardet/escsm.py \
    $$PWD/requests/packages/chardet/eucjpprober.py \
    $$PWD/requests/packages/chardet/euckrfreq.py \
    $$PWD/requests/packages/chardet/euckrprober.py \
    $$PWD/requests/packages/chardet/euctwfreq.py \
    $$PWD/requests/packages/chardet/euctwprober.py \
    $$PWD/requests/packages/chardet/gb2312freq.py \
    $$PWD/requests/packages/chardet/gb2312prober.py \
    $$PWD/requests/packages/chardet/hebrewprober.py \
    $$PWD/requests/packages/chardet/jisfreq.py \
    $$PWD/requests/packages/chardet/jpcntx.py \
    $$PWD/requests/packages/chardet/langbulgarianmodel.py \
    $$PWD/requests/packages/chardet/langcyrillicmodel.py \
    $$PWD/requests/packages/chardet/langgreekmodel.py \
    $$PWD/requests/packages/chardet/langhebrewmodel.py \
    $$PWD/requests/packages/chardet/langhungarianmodel.py \
    $$PWD/requests/packages/chardet/langthaimodel.py \
    $$PWD/requests/packages/chardet/latin1prober.py \
    $$PWD/requests/packages/chardet/mbcharsetprober.py \
    $$PWD/requests/packages/chardet/mbcsgroupprober.py \
    $$PWD/requests/packages/chardet/mbcssm.py \
    $$PWD/requests/packages/chardet/sbcharsetprober.py \
    $$PWD/requests/packages/chardet/sbcsgroupprober.py \
    $$PWD/requests/packages/chardet/sjisprober.py \
    $$PWD/requests/packages/chardet/universaldetector.py \
    $$PWD/requests/packages/chardet/utf8prober.py \
    $$PWD/requests/packages/urllib3/contrib/__init__.py \
    $$PWD/requests/packages/urllib3/contrib/ntlmpool.py \
    $$PWD/requests/packages/urllib3/contrib/pyopenssl.py \
    $$PWD/requests/packages/urllib3/packages/ssl_match_hostname/__init__.py \
    $$PWD/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py \
    $$PWD/requests/packages/urllib3/packages/__init__.py \
    $$PWD/requests/packages/urllib3/packages/ordered_dict.py \
    $$PWD/requests/packages/urllib3/packages/six.py \
    $$PWD/requests/packages/urllib3/util/__init__.py \
    $$PWD/requests/packages/urllib3/util/connection.py \
    $$PWD/requests/packages/urllib3/util/request.py \
    $$PWD/requests/packages/urllib3/util/response.py \
    $$PWD/requests/packages/urllib3/util/retry.py \
    $$PWD/requests/packages/urllib3/util/ssl_.py \
    $$PWD/requests/packages/urllib3/util/timeout.py \
    $$PWD/requests/packages/urllib3/util/url.py \
    $$PWD/requests/packages/urllib3/__init__.py \
    $$PWD/requests/packages/urllib3/_collections.py \
    $$PWD/requests/packages/urllib3/connection.py \
    $$PWD/requests/packages/urllib3/connectionpool.py \
    $$PWD/requests/packages/urllib3/exceptions.py \
    $$PWD/requests/packages/urllib3/fields.py \
    $$PWD/requests/packages/urllib3/filepost.py \
    $$PWD/requests/packages/urllib3/poolmanager.py \
    $$PWD/requests/packages/urllib3/request.py \
    $$PWD/requests/packages/urllib3/response.py \
    $$PWD/requests/packages/__init__.py \
    $$PWD/requests/__init__.py \
    $$PWD/requests/adapters.py \
    $$PWD/requests/api.py \
    $$PWD/requests/auth.py \
    $$PWD/requests/certs.py \
    $$PWD/requests/compat.py \
    $$PWD/requests/cookies.py \
    $$PWD/requests/exceptions.py \
    $$PWD/requests/hooks.py \
    $$PWD/requests/models.py \
    $$PWD/requests/sessions.py \
    $$PWD/requests/status_codes.py \
    $$PWD/requests/structures.py \
    $$PWD/requests/utils.py
